name: Tests of script.sh
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test №1
        run: |
          chmod +x script.sh
          ./script.sh ./tests/file1.sh
          echo "Pass1234" | ./tests/file1.sh.enc.sh
      - name: Test №2
        run: |
          chmod +x script.sh
          ./script.sh ./tests/file2.sh
          ./tests/file2.sh.enc.sh
      - name: Test №3
        run: |
          chmod +x script.sh
          ./script.sh ./tests/file3.sh
          echo "3" | ./tests/file3.sh.enc.sh
